"""
AlphaAgent — Paper Trading Engine

Simulates live trading without real money. Every signal generated by the
AlphaAgent pipeline can be "executed" virtually:

  - Records the signal with entry price, direction, conviction, and agent reasoning
  - After hold_days trading days, fetches the actual exit price from yfinance
  - Computes realized P&L and records whether the direction call was correct
  - Maintains a running equity curve starting from a virtual $100 000

Persistence:
  Paper trades are stored in a dedicated SQLite table (paper_trades).
  The DatabaseManager is extended at runtime with the PaperTrade model.

Daily summary:
  summarize() returns a dict with running P&L, accuracy, Sharpe (if enough data),
  recent trade journal, and agent-level accuracy breakdown.
"""

import logging
from pathlib import Path
from datetime import datetime, timedelta, timezone
from typing import Optional, List, Dict, Any

import numpy as np
import pandas as pd
import yfinance as yf
from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, Boolean, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import func

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_DB_PATH = _PROJECT_ROOT / "paper_trading.db"
DB_URL = f"sqlite:///{_DB_PATH}"

Base = declarative_base()

INITIAL_CAPITAL = 100_000.0
HOLD_DAYS = 5                   # trading days before we resolve the trade
MAX_POSITION_PCT = 0.10         # max 10% of virtual capital per signal


# ── ORM Model ────────────────────────────────────────────────────────────────

class PaperTrade(Base):
    __tablename__ = "paper_trades"

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), nullable=False, index=True)
    direction = Column(String(10))           # LONG | SHORT | HOLD
    probability = Column(Float)              # Bayesian posterior P(up)
    conviction_pct = Column(Float)
    entry_price = Column(Float)
    entry_date = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    # Resolved after hold_days
    exit_price = Column(Float, nullable=True)
    exit_date = Column(DateTime(timezone=True), nullable=True)
    gross_return_pct = Column(Float, nullable=True)
    net_return_pct = Column(Float, nullable=True)
    correct_direction = Column(Boolean, nullable=True)
    is_open = Column(Boolean, default=True, index=True)

    # Context (agent reasoning snapshot)
    agent_votes = Column(JSON, nullable=True)  # [{agent, vote, prob}]
    warnings = Column(JSON, nullable=True)
    override_reason = Column(String, nullable=True)

    # Position sizing
    position_pct = Column(Float, default=MAX_POSITION_PCT)
    position_value = Column(Float, nullable=True)


# ── Engine ────────────────────────────────────────────────────────────────────

class PaperTrader:
    """
    Main paper trading interface.

    Usage:
        trader = PaperTrader()
        trade_id = trader.record_signal(ticker, signal_packet)
        trader.resolve_open_trades()      # call daily to close expired positions
        summary = trader.summarize()
    """

    TC_BPS = 7.0          # round-trip transaction cost (base + bid-ask)
    _tc = TC_BPS / 10_000

    def __init__(self, db_url: str = DB_URL, initial_capital: float = INITIAL_CAPITAL):
        self.initial_capital = initial_capital
        self.engine = create_engine(db_url, connect_args={"check_same_thread": False})
        self.SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=self.engine)
        Base.metadata.create_all(bind=self.engine)

    # ── Signal recording ──────────────────────────────────────────────────────

    def record_signal(
        self,
        ticker: str,
        signal_packet,          # agents.state.SignalPacket
        probability_up: float = 0.5,
        position_pct: float = MAX_POSITION_PCT,
    ) -> int:
        """
        Logs a paper trade from a SignalPacket. Returns the trade ID.
        HOLD signals are not executed (returns -1).
        probability_up should be the Bayesian posterior from the orchestrator.
        """
        from agents.state import Direction
        direction = str(signal_packet.direction.value
                        if hasattr(signal_packet.direction, "value")
                        else signal_packet.direction)

        if direction == "HOLD":
            return -1

        try:
            entry_price = float(
                yf.Ticker(ticker).history(period="1d")["Close"].iloc[-1]
            )
        except Exception:
            logger.warning(f"[Paper] Could not fetch entry price for {ticker}.")
            return -1

        virtual_capital = self._get_virtual_capital()
        position_value = virtual_capital * position_pct

        agent_votes = [
            {"agent": r.agent_name, "vote": str(r.vote), "prob": round(r.probability_up, 3)}
            for r in (signal_packet.agent_results or [])
        ]

        db = self.SessionLocal()
        try:
            trade = PaperTrade(
                ticker=ticker,
                direction=direction,
                probability=float(probability_up),
                conviction_pct=float(signal_packet.conviction_pct),
                entry_price=entry_price,
                agent_votes=agent_votes,
                warnings=list(signal_packet.warnings or []),
                override_reason=signal_packet.override_reason or None,
                position_pct=position_pct,
                position_value=position_value,
                is_open=True,
            )
            db.add(trade)
            db.commit()
            db.refresh(trade)
            logger.info(f"[Paper] Recorded {direction} trade on {ticker} @ ${entry_price:.2f} (id={trade.id}).")
            return trade.id
        finally:
            db.close()

    # ── Trade resolution ──────────────────────────────────────────────────────

    def resolve_open_trades(self) -> List[Dict[str, Any]]:
        """
        Checks all open trades. For any trade where entry_date + HOLD_DAYS
        trading days have elapsed, fetches the current price and closes it.
        Returns a list of resolved trade summaries.
        """
        db = self.SessionLocal()
        try:
            open_trades = db.query(PaperTrade).filter(PaperTrade.is_open == True).all()
            resolved = []

            for trade in open_trades:
                entry_ts = trade.entry_date
                if entry_ts.tzinfo is None:
                    entry_ts = entry_ts.replace(tzinfo=timezone.utc)
                elapsed_calendar = (datetime.now(timezone.utc) - entry_ts).days
                # Approximate: 5 trading days ≈ 7 calendar days
                if elapsed_calendar < int(HOLD_DAYS * 7 / 5):
                    continue

                try:
                    hist = yf.Ticker(trade.ticker).history(period="2d")
                    if hist.empty:
                        continue
                    exit_price = float(hist["Close"].iloc[-1])
                except Exception:
                    continue

                gross_ret = (exit_price - trade.entry_price) / trade.entry_price
                if trade.direction == "SHORT":
                    gross_ret = -gross_ret
                    gross_ret -= self._tc * 5 / 252  # borrow cost
                net_ret = gross_ret - self._tc

                correct = (
                    (trade.direction == "LONG" and net_ret > 0) or
                    (trade.direction == "SHORT" and net_ret < 0)
                )

                trade.exit_price = exit_price
                trade.exit_date = datetime.now(timezone.utc)
                trade.gross_return_pct = round(gross_ret * 100, 4)
                trade.net_return_pct = round(net_ret * 100, 4)
                trade.correct_direction = correct
                trade.is_open = False

                resolved.append({
                    "id": trade.id,
                    "ticker": trade.ticker,
                    "direction": trade.direction,
                    "entry_price": trade.entry_price,
                    "exit_price": exit_price,
                    "net_return_pct": trade.net_return_pct,
                    "correct_direction": correct,
                })

            db.commit()
            return resolved
        finally:
            db.close()

    # ── Portfolio summary ─────────────────────────────────────────────────────

    def _get_virtual_capital(self) -> float:
        """Computes current virtual capital from closed trade P&Ls."""
        db = self.SessionLocal()
        try:
            closed = db.query(PaperTrade).filter(PaperTrade.is_open == False).all()
            capital = self.initial_capital
            for t in closed:
                if t.net_return_pct is not None and t.position_value:
                    capital += t.position_value * (t.net_return_pct / 100)
            return capital
        finally:
            db.close()

    def summarize(self) -> Dict[str, Any]:
        """
        Returns a full paper trading summary:
          - Equity curve, total P&L, accuracy
          - Sharpe ratio (if ≥ 30 closed trades)
          - Trade journal (last 20)
          - Per-agent accuracy breakdown
        """
        db = self.SessionLocal()
        try:
            all_trades = db.query(PaperTrade).order_by(PaperTrade.entry_date).all()
            closed = [t for t in all_trades if not t.is_open]
            open_trades = [t for t in all_trades if t.is_open]

            if not closed:
                return {
                    "virtual_capital": self.initial_capital,
                    "total_pnl": 0.0,
                    "total_pnl_pct": 0.0,
                    "n_closed_trades": 0,
                    "n_open_trades": len(open_trades),
                    "directional_accuracy_pct": None,
                    "sharpe_ratio": None,
                    "omega_ratio": None,
                    "journal": [],
                    "agent_accuracy": {},
                    "equity_curve": [],
                }

            # ── Equity curve ──────────────────────────────────────────────────
            capital = self.initial_capital
            equity_series: List[float] = [capital]
            pnl_series: List[float] = []
            dates: List[str] = []

            for t in closed:
                if t.net_return_pct is not None and t.position_value:
                    delta = t.position_value * (t.net_return_pct / 100)
                    capital += delta
                    pnl_series.append(delta / self.initial_capital)
                equity_series.append(capital)
                dates.append(t.exit_date.strftime("%Y-%m-%d") if t.exit_date else "")

            virtual_capital = capital
            total_pnl = virtual_capital - self.initial_capital
            total_pnl_pct = total_pnl / self.initial_capital * 100

            # ── Accuracy ──────────────────────────────────────────────────────
            correct_trades = [t for t in closed if t.correct_direction]
            accuracy = len(correct_trades) / len(closed) * 100

            # ── Sharpe from P&L series ────────────────────────────────────────
            sharpe = None
            omega = None
            if len(pnl_series) >= 10:
                p = np.array(pnl_series)
                rf_per_trade = (1.05 ** (HOLD_DAYS / 252)) - 1
                excess = p - rf_per_trade
                if excess.std() > 0:
                    trades_per_year = 252 / HOLD_DAYS
                    sharpe = round(float(excess.mean() / excess.std() * np.sqrt(trades_per_year)), 3)
                above = p[p > rf_per_trade] - rf_per_trade
                below = rf_per_trade - p[p <= rf_per_trade]
                if below.sum() > 0:
                    omega = round(float(above.sum() / below.sum()), 3)

            # ── Journal (last 20 closed) ──────────────────────────────────────
            journal = [
                {
                    "id": t.id,
                    "ticker": t.ticker,
                    "direction": t.direction,
                    "entry_price": t.entry_price,
                    "exit_price": t.exit_price,
                    "net_return_pct": t.net_return_pct,
                    "correct": t.correct_direction,
                    "conviction_pct": t.conviction_pct,
                    "entry_date": t.entry_date.strftime("%Y-%m-%d") if t.entry_date else "",
                    "exit_date": t.exit_date.strftime("%Y-%m-%d") if t.exit_date else "",
                    "warnings": t.warnings or [],
                    "override": t.override_reason or "",
                }
                for t in reversed(closed[-20:])
            ]

            # ── Per-agent accuracy ────────────────────────────────────────────
            agent_correct: Dict[str, List[bool]] = {}
            for t in closed:
                if not t.agent_votes or t.correct_direction is None:
                    continue
                for vote_info in t.agent_votes:
                    agent = vote_info.get("agent", "unknown")
                    vote_dir = vote_info.get("vote", "HOLD")
                    actual_correct = (
                        (vote_dir == "LONG" and t.direction == "LONG" and t.correct_direction) or
                        (vote_dir == "SHORT" and t.direction == "SHORT" and t.correct_direction) or
                        (vote_dir == "HOLD")
                    )
                    agent_correct.setdefault(agent, []).append(actual_correct)

            agent_accuracy = {
                agent: round(sum(vals) / len(vals) * 100, 1)
                for agent, vals in agent_correct.items()
                if vals
            }

            return {
                "virtual_capital": round(virtual_capital, 2),
                "total_pnl": round(total_pnl, 2),
                "total_pnl_pct": round(total_pnl_pct, 2),
                "n_closed_trades": len(closed),
                "n_open_trades": len(open_trades),
                "directional_accuracy_pct": round(accuracy, 1),
                "sharpe_ratio": sharpe,
                "omega_ratio": omega,
                "journal": journal,
                "agent_accuracy": agent_accuracy,
                "equity_curve": [
                    {"date": d, "value": round(v, 2)}
                    for d, v in zip(["start"] + dates, equity_series)
                ],
            }
        finally:
            db.close()

    def get_open_trades(self) -> List[Dict[str, Any]]:
        """Returns all currently open (unresolved) paper trades."""
        db = self.SessionLocal()
        try:
            trades = db.query(PaperTrade).filter(PaperTrade.is_open == True).all()
            return [
                {
                    "id": t.id,
                    "ticker": t.ticker,
                    "direction": t.direction,
                    "entry_price": t.entry_price,
                    "entry_date": t.entry_date.strftime("%Y-%m-%d") if t.entry_date else "",
                    "conviction_pct": t.conviction_pct,
                    "position_pct": t.position_pct,
                }
                for t in trades
            ]
        finally:
            db.close()

    def get_daily_report(self) -> str:
        """Generates a plain-text daily summary for logging/alerting."""
        s = self.summarize()
        lines = [
            "═══════════════════════════════",
            " AlphaAgent Paper Trading Report",
            "═══════════════════════════════",
            f" Virtual Capital : ${s['virtual_capital']:,.2f}",
            f" Total P&L       : ${s['total_pnl']:+,.2f} ({s['total_pnl_pct']:+.1f}%)",
            f" Trades          : {s['n_closed_trades']} closed | {s['n_open_trades']} open",
            f" Accuracy        : {s['directional_accuracy_pct']}%"
            if s['directional_accuracy_pct'] is not None else " Accuracy        : N/A",
            f" Sharpe Ratio    : {s['sharpe_ratio']}"
            if s['sharpe_ratio'] is not None else " Sharpe Ratio    : N/A (insufficient data)",
            "───────────────────────────────",
            " Recent Trades:",
        ]
        for t in s["journal"][:5]:
            sign = "✓" if t["correct"] else "✗"
            lines.append(
                f"  {sign} {t['ticker']:6s} {t['direction']:5s}  "
                f"{t['net_return_pct']:+.2f}%  (conv={t['conviction_pct']:.0f}%)"
            )
        lines.append("═══════════════════════════════")
        return "\n".join(lines)
